Edit README for db design
orix1944/chat-space pull request #2
Opened 2019-03-10 11:56 UTC by orix1944

#what
データベース設計を作ってみた
#why
今後のデータベース設計に役立てるため

2019-03-10 11:59 UTC, yuki-uchida requested changes

2019-03-10 11:59 UTC, yuki-uchida commented on README.md
> +|body    |text   |null: false, foreign_key: true|
これでは画像だけでは投稿できなくなってしまいますね

2019-03-10 11:59 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
外部キーを使用する場合にはrefferenceと書きましょう

2019-03-10 11:59 UTC, yuki-uchida commented on README.md
> +|group_name|string|null: false, foreign_key: true|
nameでいいですよ

2019-03-10 12:42 UTC, orix1944 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
カラムの種類をrefferenceに変えたら良いのでしょうか？

2019-03-10 12:43 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
そうです！

2019-03-10 12:43 UTC, yuki-uchida commented
いくつかrefference型に変えれるところがありますね

2019-03-10 12:56 UTC, orix1944 commented
ここだと思ったところを変えてみました。。。

2019-03-10 12:59 UTC, yuki-uchida requested changes
refferenceをつけている場所は良いです！

2019-03-10 12:59 UTC, yuki-uchida commented on README.md
> +|image   |string |null: true, foreign_key: true|
foreign_key、とりあえず設定していませんか？全部につければ良いわけではないので、もう一度調べてみてください。ちなみにbody,imageは不要です

2019-03-10 13:03 UTC, orix1944 commented on README.md
> +|image   |string |null: true, foreign_key: true|
分かりました。またあしたチャレンジします。。。

2019-03-11 03:06 UTC, orix1944 commented on README.md
> +|image   |string |null: true, foreign_key: true|
お早うございます。本日もお願い致します。

2019-03-11 03:14 UTC, hirozak commented on README.md
> +|nickname|text|null: false|
stringにしてindexつけましょう

2019-03-11 03:14 UTC, hirozak commented on README.md
> +- has many :messages
これ不要ですね

2019-03-11 03:26 UTC, orix1944 commented on README.md
> +|nickname|text|null: false|
変更してみました、、

2019-03-11 03:36 UTC, TOMARUMARU commented
中間テーブルを用いた多対多のアソシエーションについて調べて修正をお願いします

2019-03-11 04:15 UTC, orix1944 commented
associationを変更しました、、

2019-03-11 04:21 UTC, miyagit commented on README.md
> +- accepts_nested_attributes_for :group_users
こちら必要ないですね。

2019-03-11 04:21 UTC, miyagit commented on README.md
> +- accepts_nested_attributes_for :group_users
こちら必要ないですね。

2019-03-11 04:21 UTC, miyagit commented on README.md
> +- accepts_nested_attributes_for :group_users
messageのアソシエーションを追加しましょう。

2019-03-11 04:31 UTC, orix1944 commented on README.md
> +- accepts_nested_attributes_for :group_users
これであっているのでしょうか、、

2019-03-11 04:34 UTC, hirozak commented on README.md
> +- accepts_nested_attributes_for :group_users
`accepts_nested_attributes_for :group_users`
が必要ないということです。
アソシエーション見直してもう一度提出してください

2019-03-11 04:43 UTC, orix1944 commented on README.md
> +- accepts_nested_attributes_for :group_users
自分的にはこれが綺麗な形なのかなと考えました。

2019-03-11 04:44 UTC, hirozak commented on README.md
> +- belongs_to :user_group
`belongs_to :user_group`
これ不要です

2019-03-11 04:44 UTC, hirozak commented on README.md
> +- has_many :messages
`has_many :messages`
これ不要です

2019-03-11 04:44 UTC, hirozak commented on README.md
> +- has_many :group_users
messagesとのアソシエーションがないですね

2019-03-11 04:44 UTC, hirozak commented on README.md
> +- has_many :group_users
messagesとのアソシエーションがないですね

2019-03-11 04:47 UTC, orix1944 commented on README.md
> +- belongs_to :user_group
指摘されたところを取り除きました。

2019-03-11 04:52 UTC, orix1944 commented on README.md
> +- has_many :group_users
これでよろしいでしょうか

2019-03-11 04:53 UTC, hzak2xx approved these changes
LGTM

2019-03-11 04:56 UTC, orix1944 commented
ありがとうございました。。

2019-03-11 04:56 UTC, merged